"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, ArrowUpRight, BookOpen, Check, CheckCircle2, ChevronRight, CircleHelp, Cpu, FileText, LayoutDashboard, LogOut, Menu, MessageCircle, Plus, Send, Settings2, ShieldCheck, Sparkles, Users, X, Zap } from "lucide-react";
import { Brand, CPMark } from "./brand";
import { previewDemoImport, roleLabels, roles, sampleBillTotal, sampleMembers, type DemoRole } from "@/lib/demo";

type View = "overview" | "bills" | "board" | "members" | "settings";
type Modal = "bill" | "import" | "settings" | null;
type Message = { id: number; author: "cp" | "you"; text: string; source?: string };

function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={ref} className="dialog" onCancel={close} aria-labelledby="dialog-title"><div className="dialog-header"><div><span className="eyebrow blue">SYNTHETIC PREVIEW</span><h2 id="dialog-title">{title}</h2></div><button className="icon-button" onClick={close} aria-label="Close dialog"><X size={20} /></button></div>{children}</dialog>;
}

export function Workspace({ role }: { role: DemoRole }) {
  const router = useRouter();
  const [view, setView] = useState<View>("overview");
  const [mobileMenu, setMobileMenu] = useState(false);
  const [modal, setModal] = useState<Modal>(null);
  const [chatOpen, setChatOpen] = useState(false);
  const [chatInput, setChatInput] = useState("");
  const [sending, setSending] = useState(false);
  const [messages, setMessages] = useState<Message[]>([{ id: 0, author: "cp", text: "Hi, I’m CP. Let’s make energy a little clearer. This preview uses scripted help, so you can explore without connecting an AI account. What would you like to know?" }]);
  const [kwh, setKwh] = useState("300");
  const [rate, setRate] = useState("10");
  const [billSaved, setBillSaved] = useState(false);
  const [csv, setCsv] = useState("email\nalex@demo.example\nsam@demo.example\nalex@demo.example");
  const [importPreview, setImportPreview] = useState(false);
  const [invites, setInvites] = useState(0);
  const [notice, setNotice] = useState("");
  const [post, setPost] = useState("");
  const [posts, setPosts] = useState([{ id: 1, author: "Maya · Demo community team", title: "A little introduction goes a long way.", text: "Welcome to our sample community! What would you like to understand about your energy bill? Share a question below — keep personal account details private.", time: "Sample announcement", tag: "WELCOME" }]);
  const chatEnd = useRef<HTMLDivElement>(null);
  const chatField = useRef<HTMLInputElement>(null);
  const cpButton = useRef<HTMLButtonElement>(null);
  const chatBusy = useRef(false);
  useEffect(() => { window.scrollTo({ top: 0, behavior: "instant" }); }, [role]);
  useEffect(() => { if (chatOpen) { chatField.current?.focus(); chatEnd.current?.scrollIntoView({ block: "nearest" }); } }, [chatOpen, messages]);
  const isConsumer = role === "consumer";
  const isCommunity = role === "community-admin";
  const total = kwh.trim() && rate.trim() ? sampleBillTotal(Number(kwh), Number(rate)) : null;
  const importRows = previewDemoImport(csv);
  const readyCount = importRows.filter(row => row.status === "Ready").length;

  function navigate(next: View) { setView(next); setMobileMenu(false); setNotice(""); }
  function closeChat() { setChatOpen(false); cpButton.current?.focus(); }
  async function ask(text: string) {
    if (!text.trim() || chatBusy.current) return;
    chatBusy.current = true; setSending(true); setChatInput(""); setChatOpen(true);
    setMessages(previous => [...previous, { id: Date.now(), author: "you", text: text.trim().slice(0, 500) }]);
    try {
      const response = await fetch("/api/demo/cp", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text.trim().slice(0, 500) }) });
      if (!response.ok) throw new Error("Help unavailable");
      const answer = await response.json() as { text: string; source: string };
      setMessages(previous => [...previous, { id: Date.now() + 1, author: "cp", ...answer }]);
    } catch { setMessages(previous => [...previous, { id: Date.now() + 1, author: "cp", text: "The preview guide is unavailable right now. You can still use the direct task buttons or open the help page.", source: "/help/preview" }]); }
    finally { chatBusy.current = false; setSending(false); }
  }

  function addPost(event: FormEvent) {
    event.preventDefault(); if (!post.trim()) return;
    setPosts(previous => [{ id: Date.now(), author: "You · Demo member", title: "A new community note", text: post.trim(), time: "Just now · session only", tag: "CONVERSATION" }, ...previous]); setPost(""); setNotice("Your demo note is visible in this session. It resets when you reload.");
  }

  const navItems: { label: string; view?: View; icon: typeof Users; chat?: boolean }[] = [
    { label: "Overview", view: "overview", icon: LayoutDashboard },
    { label: "Ask CP", icon: Sparkles, chat: true },
    ...(isConsumer ? [{ label: "My energy", view: "bills" as View, icon: Zap }] : [{ label: isCommunity ? "Members" : "Communities", view: "members" as View, icon: Users }]),
    { label: "Community board", view: "board", icon: MessageCircle },
    ...(!isConsumer && !isCommunity ? [{ label: "AI & platform", view: "settings" as View, icon: Settings2 }] : []),
  ];

  return <div className="workspace">
    <aside className={`sidebar ${mobileMenu ? "sidebar-open" : ""}`}><div className="sidebar-brand"><Brand /><button className="icon-button mobile-only" aria-label="Close menu" onClick={() => setMobileMenu(false)}><X size={19} /></button></div><div className="community-selector"><span className="community-icon"><Users size={18} /></span><span>{role === "platform-admin" ? "Sandz workspace" : "Mabuhay Community"}<small>{role === "platform-admin" ? "Platform administration" : "Sample community · Philippines"}</small></span></div><span className="nav-label">YOUR WORKSPACE</span><nav aria-label="Workspace navigation">{navItems.map(({ label, view: next, icon: Icon, chat }) => <button key={label} className={`nav-item ${view === next ? "active" : ""}`} onClick={() => chat ? setChatOpen(true) : navigate(next!)}><Icon size={19} /><span>{label}</span>{chat && <span className="new-badge">CP</span>}</button>)}</nav><div className="sidebar-bottom"><div className="community-promise"><ShieldCheck size={20} /><strong>Your community.<br />Your choice.</strong><p>Clarity first. Always.</p></div><Link className="nav-item" href="/help/preview"><CircleHelp size={19} /> Help & preview guide</Link><Link className="nav-item" href="/"><LogOut size={18} /> Back to website</Link><div className="sidebar-profile"><span className="avatar">{role === "platform-admin" ? "SZ" : "AD"}</span><span>{role === "platform-admin" ? "Sandz demo" : "Alex Demo"}<small>{roleLabels[role]}</small></span><span className="online-dot" /></div></div></aside>
    {mobileMenu && <button className="menu-scrim" aria-label="Dismiss menu" onClick={() => setMobileMenu(false)} />}
    <div className="workspace-body"><header className="workspace-header"><div className="breadcrumb"><button className="icon-button mobile-only" aria-label="Open menu" onClick={() => setMobileMenu(true)}><Menu size={21} /></button><span>Workspace</span><ChevronRight size={14} /><strong>{view === "overview" ? "Overview" : view === "bills" ? "My energy" : view === "board" ? "Community board" : view === "members" ? isCommunity ? "Members" : "Communities" : "AI & platform"}</strong></div><div className="header-tools"><span className="demo-dot">Demo mode</span><label className="role-control"><span className="sr-only">Preview role</span><select aria-label="Preview role" value={role} onChange={event => router.push(`/demo/${event.target.value}`)}>{roles.map(item => <option key={item} value={item}>{roleLabels[item]}</option>)}</select></label></div></header>
    <main id="main" className="workspace-main"><div className="demo-banner"><span className="label-chip">FIRST LOOK</span><span>Synthetic data. Session-only changes. No live AI or connected accounts.</span><Link href="/help/preview">Preview guide <ArrowUpRight size={13} /></Link></div>
      {notice && <div role="status" className="notice"><CheckCircle2 size={18} />{notice}<button onClick={() => setNotice("")} aria-label="Dismiss notification"><X size={16} /></button></div>}
      {view === "overview" && <>
        <div className="page-heading"><div><span className="eyebrow muted">{isConsumer ? "YOUR COMMUNITY ENERGY SPACE" : isCommunity ? "COMMUNITY COORDINATION" : "PLATFORM OPERATIONS"}</span><h1>{isConsumer ? "Good things start together." : isCommunity ? "A connected community." : "A clearer view of the platform."}</h1><p>{isConsumer ? "Welcome, Alex. Let’s make your energy a little clearer." : isCommunity ? "A little coordination can make a meaningful difference." : "Keep communities supported, connected and in control."}</p></div><span className="date-label">25 SEP 2026 <span>DEMO SNAPSHOT</span></span></div>
        <section className="cp-welcome"><div className="welcome-text"><span className="eyebrow blue"><Sparkles size={14} /> A LITTLE HELP FROM CP</span><h2>{isConsumer ? <>Your energy questions.<br />A simpler place to start.</> : isCommunity ? <>Less admin.<br />More community.</> : <>Good support.<br />Stronger connections.</>}</h2><p>{isConsumer ? "Understand a sample bill, explore the community, or ask me where to begin." : isCommunity ? "Try a consumer import, check your sample roster, or explore the community board." : "Explore sample community status and see what’s next for your platform."}</p><div className="welcome-actions"><button className="button button-blue" onClick={() => setChatOpen(true)}>Let’s talk <ArrowRight size={17} /></button><span className="assistant-note">Scripted guide · no AI connected</span></div></div><div className="welcome-art"><div className="welcome-orbit" /><CPMark size={174} priority /><span className="hello-pill">Hello, I’m CP <Sparkles size={13} /></span></div></section>
        <div className="stat-grid">{(isConsumer ? [
          { label: "Sample monthly use", value: "300", suffix: "kWh", detail: "Illustrative bill · September", icon: Zap, color: "blue" },
          { label: "Sample bill total", value: "₱3,000", suffix: "", detail: "Example only · not your actual bill", icon: FileText, color: "yellow" },
          { label: "Your participation", value: "Free", suffix: "tier", detail: "Basic features, meaningful connection", icon: Users, color: "mint" },
        ] : isCommunity ? [
          { label: "Sample roster", value: "3", suffix: "members", detail: "2 active · 1 invited", icon: Users, color: "blue" },
          { label: "Staged this session", value: String(invites), suffix: "invites", detail: "Demo only · no emails sent", icon: Send, color: "yellow" },
          { label: "Community board", value: String(posts.length), suffix: "updates", detail: "A shared place to get connected", icon: MessageCircle, color: "mint" },
        ] : [
          { label: "Sample communities", value: "2", suffix: "spaces", detail: "Interface fixtures · not provisioned", icon: Users, color: "blue" },
          { label: "AI connection", value: "Not set", suffix: "", detail: "Provider and key still to configure", icon: Cpu, color: "yellow" },
          { label: "Build status", value: "Preview", suffix: "", detail: "Local application · first slice", icon: ShieldCheck, color: "mint" },
        ]).map(({ label, value, suffix, detail, icon: Icon, color }) => <article className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`small-icon ${color}`}><Icon size={17} /></span></div><div className="stat-value">{value}<small>{suffix}</small></div><p>{detail}</p></article>)}</div>
        <div className="dashboard-columns"><section className="panel"><div className="panel-heading"><div><span className="eyebrow muted">ONE STEP AT A TIME</span><h2>{isConsumer ? "Make yourself at home" : "Your next steps"}</h2></div><span className="subtle-pill">GET STARTED</span></div><div className="task-list"><button className="task-row" onClick={() => setModal(isConsumer ? "bill" : isCommunity ? "import" : "settings")}><span className="task-icon"><FileText size={21} /></span><span><strong>{isConsumer ? "Let’s look at a bill" : isCommunity ? "Invite your community" : "Explore AI configuration"}</strong><small>{isConsumer ? "Review and edit a synthetic example" : isCommunity ? "Preview sample emails before staging" : "See what’s needed to connect CP"}</small></span><ArrowUpRight size={18} /></button><button className="task-row" onClick={() => navigate("board")}><span className="task-icon yellow"><MessageCircle size={21} /></span><span><strong>Say hello to your community</strong><small>Take a look at the shared message board</small></span><ArrowUpRight size={18} /></button><Link className="task-row" href="/help/preview"><span className="task-icon mint"><BookOpen size={21} /></span><span><strong>Get to know Community Power</strong><small>What works today, and what comes next</small></span><ArrowUpRight size={18} /></Link></div></section><section className="panel community-card"><div className="panel-heading"><div><span className="eyebrow muted">TOGETHER IS BETTER</span><h2>From the community</h2></div><span className="board-dot" /></div><span className="announcement-tag">WELCOME NOTE</span><h3>A little introduction goes a long way.</h3><p>This is your space to share ideas and ask questions. Good conversations start with a hello.</p><div className="community-card-footer"><div className="avatar-stack"><span>MD</span><span>AD</span><span>SD</span></div><button className="text-link" onClick={() => navigate("board")}>Visit the board <ArrowRight size={15} /></button></div></section></div>
        <div className="trust-note"><ShieldCheck size={15} /><p>Supplier-neutral. No guaranteed savings. Your data-sharing choices stay yours.</p><span>SUPPORTED BY <strong>SANDZ</strong></span></div>
      </>}
      {view === "bills" && <><div className="page-heading"><div><span className="eyebrow muted">UNDERSTAND THE NUMBERS</span><h1>Your energy, explained.</h1><p>This is a synthetic bill. No personal documents are collected.</p></div><button className="button button-blue" onClick={() => setModal("bill")}><Plus size={17} /> Review sample bill</button></div><section className="panel bill-summary"><div><span className="subtle-pill">SYNTHETIC · SEPTEMBER 2026</span><h2>Sample electricity bill</h2><p>300 kWh × illustrative ₱10.00/kWh</p><strong className="large-total">₱3,000.00</strong><p>No supplier offer or eligibility has been verified.</p></div><div className="usage-bars" aria-label="Illustrative usage for six months: 250, 280, 260, 310, 285, and 300 kWh">{[250,280,260,310,285,300].map((value, i) => <div key={i}><span style={{ height: `${value / 2}px` }} /><small>{["Apr","May","Jun","Jul","Aug","Sep"][i]}</small></div>)}</div></section><div className="inline-note"><ShieldCheck size={19} /><p>Sample arithmetic is for interface exploration. It is not a reviewed bill or a savings estimate.</p></div></>}
      {view === "members" && <><div className="page-heading"><div><span className="eyebrow muted">{isCommunity ? "PEOPLE MAKE THE COMMUNITY" : "ONE PLATFORM, DISTINCT SPACES"}</span><h1>{isCommunity ? "Your community roster." : "Community overview."}</h1><p>{isCommunity ? "Synthetic members only. Imports do not send real invitations." : "Example project cards. No Supabase projects have been provisioned."}</p></div>{isCommunity && <button className="button button-blue" onClick={() => setModal("import")}><Plus size={17} /> Import consumers</button>}</div><section className="panel table-panel"><table><caption className="sr-only">{isCommunity ? "Synthetic member roster" : "Sample community projects"}</caption><thead><tr><th>{isCommunity ? "Member" : "Community"}</th><th>{isCommunity ? "Email" : "Project"}</th><th>Status</th></tr></thead><tbody>{isCommunity ? sampleMembers.map(member => <tr key={member.email}><td><span className="table-person"><span className="avatar small">{member.name[0]}D</span>{member.name}</span></td><td>{member.email}</td><td><span className={`status-pill ${member.status === "Active" ? "green" : "amber"}`}>{member.status}</span></td></tr>) : ["Mabuhay Community", "Sunrise Community"].map(name => <tr key={name}><td>{name}</td><td>No live connection</td><td><span className="status-pill amber">Demo fixture</span></td></tr>)}</tbody></table></section></>}
      {view === "board" && <><div className="page-heading"><div><span className="eyebrow muted">A PLACE FOR ALL OF US</span><h1>The community board.</h1><p>Try a synthetic note. Session-only posts reset on reload.</p></div><span className="subtle-pill">SAMPLE COMMUNITY</span></div><div className="board-layout"><div className="posts">{posts.map(item => <article className="panel post-card" key={item.id}><div className="post-author"><span className="avatar">{item.author.startsWith("You") ? "AD" : "MD"}</span><span><strong>{item.author}</strong><small>{item.time}</small></span></div><span className="announcement-tag">{item.tag}</span><h2>{item.title}</h2><p>{item.text}</p></article>)}</div><form className="panel post-form" onSubmit={addPost}><MessageCircle size={24} /><h2>Start a conversation</h2><p>Use made-up examples. Keep personal bills, credentials and account numbers out of the board.</p><label htmlFor="post">Your demo note</label><textarea id="post" maxLength={500} required value={post} onChange={event => setPost(event.target.value)} placeholder="A question, an idea, a simple hello…" /><button className="button button-blue" type="submit">Post demo note <ArrowRight size={16} /></button></form></div></>}
      {view === "settings" && <><div className="page-heading"><div><span className="eyebrow muted">SANDZ OPERATIONS</span><h1>A thoughtful foundation.</h1><p>Configuration will be connected after secure platform authentication is implemented.</p></div></div><section className="panel settings-card"><span className="icon-tile"><Cpu size={25} /></span><div><h2>CP & AI bill reading</h2><p>No provider or API key is connected. This preview deliberately has no credential input.</p><ul><li>Server-side secret storage</li><li>Capability and MFA checks</li><li>Community scope and usage limits</li></ul><button className="button button-blue" onClick={() => setModal("settings")}>View implementation notes <ArrowUpRight size={16} /></button></div><span className="status-pill amber">Not connected</span></section></>}
    </main></div>
    <button ref={cpButton} className="cp-launcher" onClick={() => setChatOpen(!chatOpen)} aria-label={chatOpen ? "Close CP assistant" : "Open CP assistant"} aria-expanded={chatOpen} aria-controls="cp-panel"><CPMark size={52} /><span>Ask CP<small>A little clarity, on demand.</small></span>{chatOpen ? <X size={19} /> : <Sparkles size={19} />}</button>
    {chatOpen && <section className="chat-panel" id="cp-panel" aria-label="CP scripted assistant" onKeyDown={event => { if (event.key === "Escape") closeChat(); }}><header className="chat-header"><CPMark size={43} /><div><strong>Your friend, CP</strong><span><span className="status-dot" /> Scripted preview · no AI</span></div><button className="icon-button" onClick={closeChat} aria-label="Close assistant"><X size={20} /></button></header><div className="chat-messages" role="log" aria-label="Conversation" aria-live="polite">{messages.map(message => <div key={message.id} className={`chat-message ${message.author}`}><span className="chat-author">{message.author === "cp" ? "CP" : "YOU"}</span><p>{message.text}</p>{message.source && <Link href={message.source} className="source-link"><BookOpen size={12} /> Preview wiki · v1 <ArrowUpRight size={12} /></Link>}</div>)}{sending && <p role="status" className="thinking">Opening the preview guide…</p>}<div ref={chatEnd} /></div><div className="chat-suggestions">{["What can I try?", "Can I scan a bill?", "Is my data saved?"].map(question => <button key={question} disabled={sending} onClick={() => ask(question)}>{question}</button>)}</div><form className="chat-composer" onSubmit={event => { event.preventDefault(); void ask(chatInput); }}><label className="sr-only" htmlFor="cp-input">Ask CP a preview question</label><input ref={chatField} id="cp-input" maxLength={500} value={chatInput} onChange={event => setChatInput(event.target.value)} placeholder="Ask about this preview…" /><button className="send-button" aria-label="Send message" disabled={sending || !chatInput.trim()}><ArrowRight size={19} /></button></form><p className="chat-disclaimer">Use synthetic examples. Never enter passwords or API keys.</p></section>}
    {modal === "bill" && <Dialog title="Let’s explore a sample bill" close={() => setModal(null)}><p className="dialog-intro">Edit these made-up values to try the review flow. Nothing is uploaded, analyzed by AI or saved to a database.</p><div className="sample-document"><FileText size={23} /><span><strong>Sample electricity bill</strong><small>September 2026 · Synthetic example</small></span><span className="subtle-pill">DEMO</span></div><form onSubmit={event => { event.preventDefault(); if (total !== null) { setBillSaved(true); setNotice("Sample bill marked as submitted in this session. It is not reviewed or saved to a database."); setModal(null); } }}><div className="form-grid"><label>Energy used (kWh)<input type="number" min="0" max="10000" step="0.01" required value={kwh} onChange={event => setKwh(event.target.value)} /></label><label>Sample rate (PHP/kWh)<input type="number" min="0" max="100" step="0.01" required value={rate} onChange={event => setRate(event.target.value)} /></label></div><div className="calculation"><span>Illustrative total</span><strong>{total === null ? "Check the values" : total.toLocaleString("en-PH", { style: "currency", currency: "PHP" })}</strong></div><p className="field-note">Simple kWh × rate arithmetic only. Real bill charges and review are not implemented.</p><div className="dialog-actions"><button type="button" className="button button-ghost" onClick={() => setModal(null)}>Cancel</button><button className="button button-blue" disabled={total === null}><Check size={17} /> {billSaved ? "Resubmit sample" : "Submit sample for review"}</button></div></form></Dialog>}
    {modal === "import" && <Dialog title="Invite a little connection" close={() => setModal(null)}><p className="dialog-intro">Try up to 25 synthetic email rows ending in <code>.example</code>. No emails are sent. This demo supports one email column.</p><label className="field-label" htmlFor="import-rows">Sample consumer emails</label><textarea id="import-rows" className="csv-input" value={csv} maxLength={2500} onChange={event => { setCsv(event.target.value); setImportPreview(false); }} />{importPreview && <div className="import-results"><table><caption>Preview: {readyCount} ready to stage</caption><tbody>{importRows.map((row, i) => <tr key={i}><td>{row.email}</td><td><span className={`status-pill ${row.status === "Ready" ? "green" : "amber"}`}>{row.status}</span></td></tr>)}</tbody></table></div>}<div className="dialog-actions"><button className="button button-ghost" onClick={() => setModal(null)}>Cancel</button>{!importPreview ? <button className="button button-blue" onClick={() => setImportPreview(true)}>Preview rows <ArrowRight size={17} /></button> : <button className="button button-blue" disabled={readyCount === 0} onClick={() => { setInvites(previous => previous + readyCount); setNotice(`${readyCount} demo invitations staged in this session. No emails were sent.`); setModal(null); setImportPreview(false); }}>Stage {readyCount} demo invitations <Check size={17} /></button>}</div></Dialog>}
    {modal === "settings" && <Dialog title="Ready for the next connection" close={() => setModal(null)}><p className="dialog-intro">Supabase authentication, secure secret storage and live AI calls are the next integration steps. No API key is needed for this preview.</p><div className="inline-note"><ShieldCheck size={22} /><p>Never paste a key into CP chat. The future settings form will use an authenticated server endpoint and show only masked metadata.</p></div><div className="dialog-actions"><Link className="button button-ghost" href="/help/preview">Read preview guide <ArrowUpRight size={15} /></Link><button className="button button-blue" onClick={() => setModal(null)}>Got it <Check size={17} /></button></div></Dialog>}
  </div>;
}
